#!/bin/bash
# ───────────────────────────────────────────────────────────────────────────
#  EMR Elite Navigator — Audio Generator (ALL prompts)
#
#  Generates pre-recorded MP3 files for EVERY announcement so that
#  ALL voice prompts play back reliably (no mid-sentence cutoffs).
#
#  Requirements: macOS — uses the built-in `say` command (female native voice).
#  Optional:     ffmpeg or lame for MP3 conversion. Without these, output
#                will be AAC (.m4a) which Safari/Chrome also support.
#
#  Recommended voice (set VOICE below; run `say -v ?` to list):
#    Samantha   — en-US female (default; clear, professional)
#    Karen      — en-AU female (Australian English)
#    Ava        — en-US female (premium, requires download)
#    Allison    — en-US female (premium)
#    Susan      — en-US female (classic)
#
#  Usage:
#    1.  Place this script inside your pwa/ folder (next to index.html)
#    2.  chmod +x generate_audio.sh
#    3.  ./generate_audio.sh
#    4.  Audio files appear in pwa/audio/
#    5.  Commit & push pwa/ + audio/ to GitHub. Done.
#
#  The HTML auto-detects the audio files at runtime. If a file is missing,
#  the matching prompt silently falls back to live TTS.
# ───────────────────────────────────────────────────────────────────────────

set -uo pipefail

VOICE="${VOICE:-Samantha}"   # macOS female en-US voice (override: VOICE=Karen ./generate_audio.sh)
RATE="${RATE:-175}"           # words per minute
OUT_DIR="${OUT_DIR:-audio}"   # output folder

# Detect encoder
if command -v ffmpeg >/dev/null 2>&1; then
    EXT="mp3"
    convert_cmd () { ffmpeg -y -loglevel error -i "$1" -codec:a libmp3lame -qscale:a 4 "$2"; }
elif command -v lame >/dev/null 2>&1; then
    EXT="mp3"
    convert_cmd () { lame --silent --quiet -V4 "$1" "$2"; }
else
    EXT="m4a"
    echo "ℹ  No ffmpeg/lame found — generating AAC (.m4a) directly via say."
fi

mkdir -p "$OUT_DIR"

generate () {
    local key="$1"
    local text="$2"
    local out_file="$OUT_DIR/${key}.${EXT}"
    [ -f "$out_file" ] && return 0   # skip if already exists (incremental runs)

    if [ "$EXT" = "m4a" ]; then
        say -v "$VOICE" -r "$RATE" --data-format="aac" -o "$out_file" -- "$text"
    else
        local tmp_aiff
        tmp_aiff=$(mktemp -t emr-audio.XXXXXX.aiff)
        say -v "$VOICE" -r "$RATE" -o "$tmp_aiff" -- "$text"
        convert_cmd "$tmp_aiff" "$out_file"
        rm -f "$tmp_aiff"
    fi
}

echo "═══════════════════════════════════════════════════════════════════"
echo "  EMR Elite Navigator — Audio Generator"
echo "  Voice: $VOICE   Rate: $RATE wpm   Format: .${EXT}   Folder: $OUT_DIR/"
echo "═══════════════════════════════════════════════════════════════════"
echo "  Generating EMR audio files for GitHub/PWA. This takes a few minutes…"

generate "greeting" "Hello, I am a firefighter. We came to help you. Please stay still and relax. We will examine your body. Is that okay?"
generate "cc-intro" "Can you tell me what is bothering you the most right now? Please describe your main symptom."
generate "shock-intro" "May I touch your skin to check your circulation?"
generate "cpr-flow-protocol" "CPR flow. Confirm safety and responsiveness. Call emergency services and bring the AED. Check breathing and pulse within ten seconds. Start compressions at one hundred to one hundred twenty per minute. Give breaths by protocol. Analyze with the AED every two minutes. If shock is advised, clear the patient, deliver shock, and immediately resume CPR."
generate "id-card" "Can you show me your ID card, CAC, or passport if you have one?"
generate "fast-smile" "Can you smile for me? Show me your teeth."
generate "fast-arm" "Close your eyes and hold both arms straight out with your palms up for ten seconds."
generate "fast-speech" "Please repeat this phrase after me: You can't teach an old dog new tricks."
generate "med-q1" "Is this medication prescribed to you personally by a doctor? Please show me the label with your name on it."
generate "med-q2" "How much of this medication do you usually take, and how often? Are you about to take the correct dose right now?"
generate "med-q3" "Are your current symptoms the same ones this medication is meant to treat? For example, is the chest pain the kind your nitroglycerin is for?"
generate "opqrst-o" "When did this start, and what was happening at that moment?"
generate "opqrst-p" "What makes it worse, and what makes it better?"
generate "opqrst-q" "How would you describe the pain or sensation?"
generate "opqrst-r" "Where exactly is it, and does it spread anywhere?"
generate "opqrst-s" "On a scale of zero to ten, how severe is it right now?"
generate "opqrst-t" "How has the timing been since it started?"
generate "sample-s" "Are you experiencing any other symptoms right now?"
generate "sample-a" "Do you have any known allergies?"
generate "sample-m" "Are you taking any medications?"
generate "sample-p" "Do you have any past medical history?"
generate "sample-l" "What did you last eat or drink, and how many hours ago was that?"
generate "sample-e" "Was there anything different from your usual day today?"
generate "disp-intro" "Do you want us to call an ambulance and take you to a Japanese hospital? Or do you refuse transport?"
generate "disp-go" "Would you like us to call a Japanese ambulance and take you to a hospital for further evaluation?"
generate "disp-refuse" "Are you refusing transport to a hospital? Please understand that your condition may become worse without medical evaluation. Do you still refuse to be transported?"
generate "disp-sign" "If you still refuse transport, please read and sign the Refusal of Medical Assistance document we have prepared. Your signature confirms that you understand the risks, including possible worsening of your condition, complications, or death."
generate "cpr-start" "CPR started. Push hard. Push fast. One hundred to one hundred twenty per minute."
generate "cpr-rhythm-check" "Rhythm check. Stand clear of the patient."
generate "reassess-unstable" "Reassess vital signs. Unstable patient. Five minute interval."
generate "reassess-stable" "Reassess vital signs. Stable patient. Fifteen minute interval."
generate "triage-no-walk" "Patient cannot walk. Checking for spontaneous breathing."
generate "triage-no-breathing" "No spontaneous breathing. Executing manual airway maneuver."
generate "triage-breathing-yes" "Breathing exists. Counting respiratory rate."
generate "triage-rr-high" "Respiratory rate is 30 or more. Status is Immediate."
generate "triage-rr-low" "Respiratory rate is 29 or less. Checking perfusion or pulse."
generate "triage-crt-bad" "CRT is more than 2 seconds or pulse is absent. Status is Immediate."
generate "triage-perfusion-ok" "Perfusion checks out. Testing ability to obey commands."
generate "triage-obeys" "Patient obeys simple commands. Status is Delayed."
generate "triage-disobeys" "Patient disobeys simple commands. Status is Immediate."
generate "triage-manual-airway" "Manual airway provided. Checking for spontaneous breathing again."
generate "triage-airway-breathing" "Breathing started after manual airway. Status is Immediate."
generate "triage-deceased" "Still no breathing after manual airway. Status is Deceased."
generate "triage-complete" "Triage complete. Moving to Flow Selection."
generate "chip-chest-pain" "Are you having chest pain?"
generate "chip-difficulty-breathing" "Are you having difficulty breathing?"
generate "chip-altered-mental-status" "Do you feel confused or lightheaded?"
generate "chip-severe-headache" "Are you having a severe headache?"
generate "chip-abdominal-pain" "Are you having abdominal pain?"
generate "chip-trauma-injury" "Did you suffer any injury?"
generate "chip-back-lumbar-pain" "Are you having back or lower back pain?"
generate "chip-palpitations" "Are you feeling your heart racing or skipping?"
generate "chip-nausea-vomiting" "Are you feeling nauseous or have you vomited?"
generate "chip-numbness-paralysis" "Do you feel any numbness or weakness?"
generate "chip-convulsion-seizure" "Did you have a seizure?"
generate "chip-high-fever" "Do you have a high fever?"
generate "chip-cough" "Are you coughing?"
generate "chip-allergic-reaction" "Are you having an allergic reaction?"
generate "chip-bleeding" "Are you bleeding anywhere?"
generate "chip-stroke-facial-droop" "Can you smile and show me your teeth?"
generate "chip-stroke-arm-weakness" "Can you lift both arms and hold them up?"
generate "chip-stroke-slurred-speech" "Can you repeat this sentence after me?"
generate "chip-stroke-vision-loss" "Have you suddenly lost any vision?"
generate "chip-stroke-sudden-confusion" "Do you feel suddenly confused?"
generate "chip-cardiorespiratory-arrest" "Sir or Ma\\"
generate "chip-heat-illness" "Have you been in a hot environment for a long time?"
generate "chip-hypothermia" "Have you been exposed to cold for a long time?"
generate "chip-intoxication" "Have you taken any alcohol or drugs?"
generate "chip-none" "Do you feel any symptoms at all right now?"
generate "chip-sitting-watching-tv" "Were you sitting or watching TV when it started?"
generate "chip-standing-walking" "Were you standing or walking when it started?"
generate "chip-running-exercising" "Were you running or exercising when it started?"
generate "chip-working-lifting-heavy" "Were you working or lifting something heavy when it started?"
generate "chip-climbing-stairs" "Were you climbing stairs when it started?"
generate "chip-eating-a-meal" "Were you eating when it started?"
generate "chip-drinking-alcohol" "Were you drinking alcohol when it started?"
generate "chip-sleeping-in-bed" "Were you sleeping or in bed when it started?"
generate "chip-just-woke-up" "Did this start right after you woke up?"
generate "chip-in-the-bath-shower" "Were you in the bath or shower when it started?"
generate "chip-on-the-toilet" "Were you on the toilet when it started?"
generate "chip-driving" "Were you driving when it started?"
generate "chip-in-a-hot-environment" "Were you in a hot environment when it started?"
generate "chip-in-a-cold-environment" "Were you in a cold environment when it started?"
generate "chip-arguing-emotional-stress" "Were you arguing or under strong emotional stress when it started?"
generate "chip-taking-medication" "Were you taking medication when it started?"
generate "chip-after-an-injury" "Did this start right after an injury?"
generate "chip-nothing-in-particular" "Were you doing nothing in particular when it started?"
generate "chip-recurring-episode-same-as-before" "Have you had this exact same episode before?"
generate "chip-cannot-remember" "Do you remember what you were doing when it started?"
generate "chip-stress-anxiety" "Do you think stress or anxiety caused this?"
generate "chip-overwork-fatigue" "Do you think overwork or fatigue caused this?"
generate "chip-lack-of-sleep" "Do you think lack of sleep caused this?"
generate "chip-new-medication" "Did you start a new medication recently?"
generate "chip-skipped-routine-medication" "Did you skip your usual medication?"
generate "chip-specific-food-suspect" "Do you think a specific food caused this?"
generate "chip-alcohol" "Do you think alcohol caused this?"
generate "chip-recent-injury-accident" "Did a recent injury or accident cause this?"
generate "chip-heavy-lifting-physical-strain" "Did heavy lifting or physical strain cause this?"
generate "chip-sudden-temperature-change" "Did a sudden temperature change cause this?"
generate "chip-allergic-exposure" "Were you exposed to something you are allergic to?"
generate "chip-insect-bite-sting" "Were you bitten or stung by an insect?"
generate "chip-family-member-has-same-illness" "Does a family member have the same illness?"
generate "chip-past-similar-episode" "Have you had a similar episode before?"
generate "chip-travel-new-environment" "Did this start after travel or being in a new environment?"
generate "chip-chronic-disease-flare-up" "Could this be a flare-up of your chronic illness?"
generate "chip-pregnancy-menstrual-cycle" "Are you pregnant or having your menstrual cycle?"
generate "chip-recent-surgery-procedure" "Have you had recent surgery or a procedure?"
generate "chip-no-idea-cannot-identify" "Can you think of any possible cause?"
generate "chip-other-text-input-below" "Is there something else that may have caused this?"
generate "chip-sharp-stabbing-pain" "Is the pain sharp and stabbing?"
generate "chip-dull-heavy-ache" "Is it a dull, heavy ache?"
generate "chip-squeezing-tightness" "Does it feel squeezing or tight?"
generate "chip-burning-scalding-pain" "Is it a burning or scalding pain?"
generate "chip-heavy-crushing-pressure" "Does it feel like heavy crushing pressure?"
generate "chip-tearing-intense-pain" "Does it feel like a tearing pain?"
generate "chip-cramping-colicky" "Is it a cramping or wave-like pain?"
generate "chip-throbbing-pulsation" "Is the pain throbbing or pulsating?"
generate "chip-pressure-heaviness" "Does it feel like pressure or heaviness?"
generate "chip-itching-sensation" "Does it itch?"
generate "chip-numbness-tingling" "Do you feel numbness or tingling?"
generate "chip-electric-shock-pain" "Does it feel like an electric shock?"
generate "chip-aching" "Is it an aching feeling?"
generate "chip-sore-feeling" "Does it feel sore?"
generate "chip-suffocating-sensation" "Do you feel like you cannot breathe?"
generate "chip-air-hunger" "Do you feel short of breath, like you need more air?"
generate "chip-palpitations-skipping" "Do you feel your heart skipping or racing?"
generate "chip-spinning-vertigo" "Do you feel the room spinning?"
generate "chip-hard-to-describe" "Is it hard to describe?"
generate "chip-no-pain-other-discomfort" "Is there discomfort rather than pain?"
generate "chip-localized-completely" "Is the pain only in one place?"
generate "chip-radiating-to-left-arm-shoulder" "Does the pain spread to your left arm or shoulder?"
generate "chip-radiating-to-back" "Does the pain spread to your back?"
generate "chip-radiating-to-jaw-neck-teeth" "Does the pain spread to your jaw, neck, or teeth?"
generate "chip-radiating-to-upper-abdomen" "Does it spread to your upper belly?"
generate "chip-shifting-localization" "Has the pain moved to a different place?"
generate "chip-radiating-to-right-arm" "Does the pain spread to your right arm?"
generate "chip-radiating-to-both-arms" "Does the pain spread to both arms?"
generate "chip-radiating-to-flank" "Does the pain spread to your side?"
generate "chip-radiating-to-groin" "Does the pain spread to your groin?"
generate "chip-radiating-to-legs" "Does the pain spread to your legs?"
generate "chip-radiating-to-between-scapula" "Does the pain spread between your shoulder blades?"
generate "chip-radiating-to-chest" "Does the pain spread to your chest?"
generate "chip-radiating-to-head" "Does the pain spread to your head?"
generate "chip-radiating-to-lower-abdomen" "Does the pain spread to your lower belly?"
generate "chip-whole-body-diffuse" "Do you feel it all over your body?"
generate "chip-migratory-pain" "Does the pain move from place to place?"
generate "chip-deep-visceral" "Does it feel deep inside?"
generate "chip-surface-superficial" "Does it feel on the surface of the skin?"
generate "chip-bilateral-symmetric" "Do you feel it on both sides equally?"
generate "chip-10-10-unbearable-maximal-pain" "Is it the worst pain you have ever felt, a ten out of ten?"
generate "chip-9-10-excruciating" "Is it close to the worst pain you have ever felt?"
generate "chip-8-10-very-strong-pain" "Is it a very strong pain, about eight out of ten?"
generate "chip-7-10-severe-pain" "Is it a severe pain, around seven out of ten?"
generate "chip-6-10-strong-pain" "Is it a strong pain, around six out of ten?"
generate "chip-5-10-moderate-tolerable-pain" "Is it a moderate pain, around five out of ten?"
generate "chip-4-10-moderate-pain" "Is it a moderate pain, around four out of ten?"
generate "chip-3-10-mild-nagging-pain" "Is it a mild pain, around three out of ten?"
generate "chip-2-10-slight-pain" "Is it a slight pain, around two out of ten?"
generate "chip-1-10-barely-noticeable" "Is it barely noticeable, around one out of ten?"
generate "chip-0-10-completely-pain-free" "Are you completely pain-free now?"
generate "chip-rapidly-worsening-severity" "Is the pain getting worse quickly?"
generate "chip-gradually-improving" "Is the pain getting better gradually?"
generate "chip-stable-in-severity" "Has it stayed about the same?"
generate "chip-worst-pain-of-life" "Is it the worst pain of your life?"
generate "chip-comparable-to-past-episode" "Is it about the same as before?"
generate "chip-worse-than-previous" "Is it worse than before?"
generate "chip-milder-than-previous" "Is it milder than before?"
generate "chip-limits-daily-activities" "Does it stop you from doing daily activities?"
generate "chip-bearable-can-converse" "Can you still talk through it?"
generate "chip-constant-uninterrupted-pain" "Is it constant without any break?"
generate "chip-intermittent-with-clear-waves" "Does it come and go in clear waves?"
generate "chip-comes-and-goes-transiently" "Does it come and go briefly?"
generate "chip-continuous-for-several-hours" "Has it been continuous for several hours?"
generate "chip-first-time-experiencing-this" "Is this the first time you have felt this?"
generate "chip-similar-past-episodes-noted" "Have you felt this before in the past?"
generate "chip-started-5-minutes-ago" "Did this start less than five minutes ago?"
generate "chip-started-5-30-minutes-ago" "Did this start between five and thirty minutes ago?"
generate "chip-started-1-3-hours-ago" "Did this start one to three hours ago?"
generate "chip-started-6-hours-ago" "Did this start more than six hours ago?"
generate "chip-lasting-1-minute" "Does each episode last less than one minute?"
generate "chip-lasting-1-5-minutes" "Does each episode last one to five minutes?"
generate "chip-lasting-5-30-minutes" "Does each episode last five to thirty minutes?"
generate "chip-lasting-30-minutes" "Does each episode last more than thirty minutes?"
generate "chip-worsening-over-time" "Is it getting worse over time?"
generate "chip-improving-over-time" "Is it getting better over time?"
generate "chip-recurrent-in-days" "Has it come back over several days?"
generate "chip-recurrent-in-weeks" "Has it come back over several weeks?"
generate "chip-episodic-monthly" "Does it come back about once a month?"
generate "chip-chronic-3-months" "Have you had this for more than three months?"
generate "chip-mva-high-speed-collision" "Were you in a high speed vehicle crash?"
generate "chip-mva-low-speed-collision" "Were you in a low speed vehicle crash?"
generate "chip-motorcycle-crash" "Were you in a motorcycle crash?"
generate "chip-pedestrian-struck" "Were you struck by a vehicle while walking?"
generate "chip-fall-from-3m-10ft" "Did you fall from more than ten feet?"
generate "chip-fall-from-3m" "Did you fall from less than ten feet?"
generate "chip-fall-from-standing" "Did you fall from standing height?"
generate "chip-stair-fall" "Did you fall down stairs?"
generate "chip-blunt-assault" "Were you hit or punched by someone?"
generate "chip-penetrating-knife" "Were you stabbed?"
generate "chip-penetrating-gunshot" "Were you shot?"
generate "chip-crush-injury" "Were you crushed by something heavy?"
generate "chip-sports-injury" "Did this happen during sports?"
generate "chip-training-injury" "Did this happen during training?"
generate "chip-industrial-machinery" "Were you injured by machinery?"
generate "chip-burn-thermal" "Were you burned by heat or fire?"
generate "chip-burn-chemical" "Were you burned by a chemical?"
generate "chip-burn-electrical" "Were you injured by electricity?"
generate "chip-blast-explosion" "Were you near an explosion?"
generate "chip-drowning-water-trauma" "Were you in a water accident?"
generate "chip-worse-with-movement" "Does it get worse when you move?"
generate "chip-worse-with-weight-bearing" "Does it get worse when you put weight on it?"
generate "chip-worse-with-palpation" "Does it get worse when I touch it?"
generate "chip-better-when-immobilized" "Does it feel better when held still?"
generate "chip-better-lying-flat" "Does lying flat help?"
generate "chip-worse-when-sitting-up" "Does sitting up make it worse?"
generate "chip-worse-with-rotation" "Does turning or twisting make it worse?"
generate "chip-worse-with-cough-sneeze" "Does coughing or sneezing make it worse?"
generate "chip-no-relief-in-any-position" "Is there no position that makes it better?"
generate "chip-better-with-ice-pack" "Does an ice pack help?"
generate "chip-better-with-elevation" "Does raising it help?"
generate "chip-worse-with-passive-rom" "Does it hurt when I move it for you?"
generate "chip-worse-with-active-rom" "Does it hurt when you move it yourself?"
generate "chip-worse-with-traction" "Does pulling on it make it worse?"
generate "chip-loss-of-function" "Can you still use it?"
generate "chip-worse-with-pressure-on-wound" "Does pressing on the wound make it worse?"
generate "chip-worse-with-bending" "Does bending make it worse?"
generate "chip-no-pain-numb-area" "Do you feel any sensation at all?"
generate "chip-constant-regardless-of-position" "Is it the same no matter how you position?"
generate "chip-sharp-lacerating" "Does it feel like a sharp cut?"
generate "chip-dull-aching" "Is it a dull ache?"
generate "chip-crushing-pressure" "Does it feel like crushing pressure?"
generate "chip-burning-thermal-pain" "Is it a burning pain like a burn?"
generate "chip-throbbing" "Is it a throbbing pain?"
generate "chip-stabbing" "Is it a stabbing pain?"
generate "chip-tearing" "Does it feel like tearing?"
generate "chip-grinding-crepitus" "Do you feel grinding or crackling when you move?"
generate "chip-electric-shooting-pain" "Does it shoot like an electric shock?"
generate "chip-deep-bone-pain" "Does the pain feel deep in the bone?"
generate "chip-joint-pain" "Is the pain in the joint?"
generate "chip-muscle-spasm" "Does your muscle feel like it is cramping?"
generate "chip-cramping" "Is it cramping?"
generate "chip-pulsating-bleeding" "Is the bleeding spurting out?"
generate "chip-oozing-bleeding" "Is the bleeding slowly oozing?"
generate "chip-pins-and-needles" "Do you feel pins and needles?"
generate "chip-cold-numbness" "Does that area feel cold and numb?"
generate "chip-hot-swelling" "Does that area feel hot and swollen?"
generate "chip-no-sensation" "Do you have any feeling there?"
generate "chip-localized-to-impact-site" "Is the pain only where you were hit?"
generate "chip-radiating-along-nerve" "Does it spread along a nerve path?"
generate "chip-radiating-distally" "Does it spread down the limb?"
generate "chip-radiating-proximally" "Does it spread up the limb?"
generate "chip-referred-to-shoulder-diaphragm" "Do you feel pain in your shoulder?"
generate "chip-pelvic-pain-to-legs" "Does pelvic pain spread down your legs?"
generate "chip-spine-pain-to-extremities" "Does spine pain spread to your arms or legs?"
generate "chip-abdomen-to-back" "Does belly pain spread to your back?"
generate "chip-chest-to-arms" "Does chest pain spread to your arms?"
generate "chip-head-to-neck" "Does head pain spread to your neck?"
generate "chip-across-midline" "Does it cross to the other side of your body?"
generate "chip-multiple-injury-sites" "Do you have pain in more than one place?"
generate "chip-single-isolated-site" "Is the pain in only one spot?"
generate "chip-diffuse-generalized" "Do you feel pain all over?"
generate "chip-surface-laceration-only" "Is it only a surface cut?"
generate "chip-deep-tissue-involvement" "Does it feel deep inside?"
generate "chip-bony-tenderness" "Does the bone feel tender?"
generate "chip-muscle-compartment" "Does the muscle feel tight or swollen?"
generate "chip-no-clear-localization" "Can you point to where it hurts most?"
generate "chip-10-10-unbearable" "Is it the worst pain you have ever felt?"
generate "chip-8-10-very-severe" "Is the pain very severe, around eight out of ten?"
generate "chip-7-10-severe" "Is the pain severe, around seven out of ten?"
generate "chip-6-10-strong" "Is the pain strong, around six out of ten?"
generate "chip-5-10-moderate" "Is the pain moderate, around five out of ten?"
generate "chip-4-10-moderate-mild" "Is the pain mild to moderate, around four out of ten?"
generate "chip-3-10-mild" "Is the pain mild, around three out of ten?"
generate "chip-2-10-slight" "Is the pain slight, around two out of ten?"
generate "chip-1-10-barely-noticeable" "Is it barely noticeable?"
generate "chip-0-10-no-pain" "Do you have no pain right now?"
generate "chip-worsening-rapidly" "Is it getting worse quickly?"
generate "chip-improving-with-care" "Is it improving with treatment?"
generate "chip-stable" "Has it stayed the same?"
generate "chip-pain-on-movement-only" "Does it only hurt when you move?"
generate "chip-constant-pain" "Is the pain constant?"
generate "chip-loss-of-consciousness-with-pain" "Did you pass out from the pain?"
generate "chip-pain-prevents-speech" "Is the pain so bad you cannot speak?"
generate "chip-pain-prevents-standing" "Is the pain so bad you cannot stand?"
generate "chip-pain-tolerable-to-communicate" "Can you still communicate through the pain?"
generate "chip-just-occurred-5-min" "Did this just happen, less than five minutes ago?"
generate "chip-5-30-min-ago" "Did this happen five to thirty minutes ago?"
generate "chip-30-min-1-hr-ago" "Did this happen thirty minutes to one hour ago?"
generate "chip-1-3-hours-ago" "Did this happen one to three hours ago?"
generate "chip-3-6-hours-ago" "Did this happen three to six hours ago?"
generate "chip-6-12-hours-ago" "Did this happen six to twelve hours ago?"
generate "chip-12-24-hours-ago" "Did this happen twelve to twenty four hours ago?"
generate "chip-24-hours-ago" "Did this happen more than a day ago?"
generate "chip-continuous-since-injury" "Has the pain been constant since the injury?"
generate "chip-worsening-since-injury" "Has it gotten worse since the injury?"
generate "chip-improving-since-injury" "Has it been getting better since the injury?"
generate "chip-initially-better-then-worse" "Did you feel better at first and then worse?"
generate "chip-delayed-onset" "Did the pain come on after some time?"
generate "chip-came-on-minutes-after" "Did the pain come on a few minutes after?"
generate "chip-initial-loc-then-alert" "Did you lose consciousness and then wake up?"
generate "chip-pain-free-initially" "Did you feel no pain at first?"
generate "chip-pulse-sensation-gradually-lost" "Have you lost feeling or pulse gradually?"
generate "chip-repeated-re-injury" "Have you injured this area more than once?"
generate "chip-old-injury-reaggravated" "Did an old injury get worse again?"
generate "chip-time-of-injury-unknown" "Do you remember when the injury happened?"
generate "chip-cold-sweating-heavily" "Are you sweating heavily and feeling cold?"
generate "chip-chills-shivering" "Do you have chills or shivering?"
generate "chip-severe-dizziness-vertigo" "Are you feeling dizzy or like the room is spinning?"
generate "chip-numbness-in-extremities" "Do your arms or legs feel numb?"
generate "chip-blurry-vision" "Is your vision blurry?"
generate "chip-tachypnea-hyperventilation" "Are you breathing very fast?"
generate "chip-pale-skin-pallor" "Do you feel your skin is pale?"
generate "chip-cyanosis" "Do your lips or fingers look blue?"
generate "chip-flushed-skin" "Does your face feel flushed or hot?"
generate "chip-diaphoresis" "Are you sweating a lot?"
generate "chip-weakness-fatigue" "Do you feel weak or fatigued?"
generate "chip-loss-of-balance" "Are you losing your balance?"
generate "chip-confusion" "Do you feel confused?"
generate "chip-tinnitus" "Do you hear ringing in your ears?"
generate "chip-dry-mouth-thirst" "Do you feel very thirsty?"
generate "chip-photophobia" "Does light bother your eyes?"
generate "chip-tremor-shaking" "Are you shaking or trembling?"
generate "chip-stiff-neck" "Does your neck feel stiff?"
generate "chip-anxiety-panic" "Are you feeling anxious or panicked?"
generate "chip-no-additional-symptoms" "Do you have any other symptoms?"
generate "chip-no-known-allergies" "Do you have any allergies?"
generate "chip-penicillin-antibiotics" "Are you allergic to penicillin?"
generate "chip-aspirin-nsaids" "Are you allergic to aspirin or pain relievers?"
generate "chip-bee-stings-wasp-venom" "Are you allergic to bee or wasp stings?"
generate "chip-peanuts-eggs-wheat" "Are you allergic to any specific foods?"
generate "chip-latex-rubber" "Are you allergic to latex?"
generate "chip-iodine-contrast-media" "Are you allergic to iodine or contrast dye?"
generate "chip-shellfish-crustaceans" "Are you allergic to shellfish?"
generate "chip-tree-nuts" "Are you allergic to tree nuts?"
generate "chip-dairy-milk" "Are you allergic to dairy?"
generate "chip-soy-products" "Are you allergic to soy?"
generate "chip-buckwheat-soba" "Are you allergic to buckwheat?"
generate "chip-sulfa-drugs" "Are you allergic to sulfa drugs?"
generate "chip-local-anesthetics" "Are you allergic to local anesthetics?"
generate "chip-pollen-hay-fever" "Do you have hay fever?"
generate "chip-animal-dander" "Are you allergic to animals?"
generate "chip-dust-mites" "Are you allergic to dust?"
generate "chip-adhesive-tape" "Are you allergic to adhesive tape?"
generate "chip-unknown-uncertain" "Are you sure about your allergies?"
generate "chip-previous-anaphylaxis" "Have you ever had a severe allergic reaction before?"
generate "chip-no-routine-medications" "Are you taking any medications?"
generate "chip-nitroglycerin-spray-tablets" "Do you take nitroglycerin?"
generate "chip-epipen-adrenaline-auto-injector" "Do you carry an EpiPen?"
generate "chip-blood-thinners-anticoagulants" "Are you taking blood thinners?"
generate "chip-insulin-injections-diabetes-meds" "Are you taking insulin or diabetes medication?"
generate "chip-inhaler-asthma-bronchodilator" "Do you use an inhaler for asthma?"
generate "chip-antihypertensives" "Are you taking blood pressure medication?"
generate "chip-statins-cholesterol-meds" "Are you taking cholesterol medication?"
generate "chip-aspirin-daily-low-dose" "Do you take a daily aspirin?"
generate "chip-beta-blockers" "Are you taking beta blockers?"
generate "chip-antiarrhythmics" "Are you taking medication for irregular heartbeat?"
generate "chip-antidepressants" "Are you taking antidepressants?"
generate "chip-anxiolytics-sleep-aids" "Are you taking anti-anxiety or sleep medication?"
generate "chip-antiepileptics" "Are you taking seizure medication?"
generate "chip-steroids-cortisone" "Are you taking steroids?"
generate "chip-oral-contraceptives" "Are you taking birth control pills?"
generate "chip-otc-pain-killers" "Are you taking over-the-counter pain killers?"
generate "chip-herbal-supplements" "Are you taking any herbal supplements?"
generate "chip-chemotherapy-cancer-drugs" "Are you receiving cancer treatment?"
generate "chip-immunosuppressants" "Are you taking immunosuppressant medication?"
generate "chip-no-remarkable-medical-history" "Do you have any past medical history?"
generate "chip-severe-hypertension" "Do you have high blood pressure?"
generate "chip-diabetes-mellitus" "Do you have diabetes?"
generate "chip-angina-pectoris-myocardial-infarction" "Have you had angina or a heart attack?"
generate "chip-bronchial-asthma" "Do you have asthma?"
generate "chip-cerebral-infarction-stroke-tia" "Have you had a stroke?"
generate "chip-copd-emphysema" "Do you have COPD or emphysema?"
generate "chip-arrhythmia-afib" "Do you have an irregular heartbeat?"
generate "chip-congestive-heart-failure" "Do you have heart failure?"
generate "chip-kidney-disease-dialysis" "Do you have kidney disease or are you on dialysis?"
generate "chip-liver-disease-cirrhosis" "Do you have liver disease?"
generate "chip-cancer-malignancy" "Do you have a history of cancer?"
generate "chip-epilepsy-seizure-disorder" "Do you have epilepsy?"
generate "chip-mental-health-condition" "Do you have a mental health condition?"
generate "chip-recent-surgery" "Have you had surgery recently?"
generate "chip-recent-hospitalization" "Have you been hospitalized recently?"
generate "chip-thyroid-disease" "Do you have thyroid disease?"
generate "chip-pregnancy" "Are you pregnant?"
generate "chip-chronic-pain-disorder" "Do you have chronic pain?"
generate "chip-anemia" "Do you have anemia?"
generate "chip-regular-meal-1-hour-ago" "Did you eat a meal less than an hour ago?"
generate "chip-regular-meal-1-3-hours-ago" "Did you eat between one and three hours ago?"
generate "chip-regular-meal-3-hours-ago" "Was your last meal more than three hours ago?"
generate "chip-water-tea-only-1h" "Have you only had water or tea in the last hour?"
generate "chip-nothing-today-fasting" "Have you eaten anything today?"
generate "chip-vomited-last-meal" "Did you vomit your last meal?"
# --- New SAMPLE L chips (v2.8): time buckets + meal types ---
generate "chip-about-1-hour-ago" "Did you eat about one hour ago?"
generate "chip-about-2-hours-ago" "Did you eat about two hours ago?"
generate "chip-4-hours-ago" "Was your last meal four or more hours ago?"
generate "chip-yesterday" "Was your last meal yesterday?"
generate "chip-regular-japanese-meal" "Did you eat a regular Japanese meal?"
generate "chip-bread-toast-pasta" "Did you eat bread, toast, or pasta?"
generate "chip-rice-side-dishes" "Did you eat rice with side dishes?"
generate "chip-salad-light-meal" "Did you eat a salad or a light meal?"
generate "chip-drink-only-water-tea-coffee" "Did you only have water, tea, or coffee?"
generate "chip-nothing-fasting" "Have you eaten anything today?"
generate "chip-nothing-fasting-pre-op" "Have you been fasting before any surgery?"
generate "chip-honey-infant-1-yr" "Was honey given to the infant?"
generate "chip-shellfish-allergy" "Are you allergic to shellfish?"
generate "chip-peanuts-nuts-allergy" "Are you allergic to peanuts or nuts?"
generate "chip-buckwheat-soba-allergy" "Did you eat buckwheat or soba?"
generate "chip-patient-cannot-answer" "Please tell me when you last ate or drank."
generate "chip-raw-fish-sushi-sashimi" "Did you recently eat raw fish, sushi, or sashimi?"
generate "chip-raw-shellfish-oysters" "Did you eat raw shellfish or oysters?"
generate "chip-undercooked-chicken-eggs" "Did you eat undercooked chicken or raw eggs?"
generate "chip-reheated-rice-leftovers" "Did you eat reheated rice or leftover food?"
generate "chip-honey-infant" "Was honey given to the infant?"
generate "chip-wild-mushroom" "Did you eat any wild mushrooms?"
generate "chip-bee-venom-insect-bite" "Were you stung by a bee or bitten by an insect?"
generate "chip-buckwheat-soba" "Did you eat buckwheat or soba?"
generate "chip-peanuts-tree-nuts" "Did you eat peanuts or tree nuts?"
generate "chip-shellfish-crab-shrimp" "Did you eat shellfish, crab, or shrimp?"
generate "chip-wheat-gluten" "Did you eat anything with wheat or gluten?"
generate "chip-alcohol-hard-liquor" "How much alcohol did you drink?"
generate "chip-energy-drink-high-caffeine" "Did you drink an energy drink or a lot of caffeine?"
generate "chip-new-medication-today" "Did you take any new medication today?"
generate "chip-no-unusual-events-today" "Was today a normal day for you?"
generate "chip-felt-different-than-usual-today" "Did you feel different than usual today?"
generate "chip-skipped-routine-medication" "Did you skip any of your usual medication?"
generate "chip-less-sleep-than-usual" "Did you sleep less than usual?"
generate "chip-unusual-extreme-heat-environment" "Were you in an unusually hot environment?"
generate "chip-cold-exposure-hypothermic-env" "Were you exposed to the cold?"
generate "chip-heavy-physical-training" "Did you do heavy physical training?"
generate "chip-fell-down-from-ground-level" "Did you fall while walking?"
generate "chip-argument-high-mental-stress" "Did you have an argument or strong stress?"
generate "chip-while-sleeping-rest-period" "Did this happen while you were sleeping?"
generate "chip-suddenly-felt-sick-out-of-nowhere" "Did you suddenly feel sick out of nowhere?"
generate "chip-travel-long-distance-commute" "Have you been traveling recently?"
generate "chip-recent-illness-in-family" "Has anyone in your family been sick?"
generate "chip-new-environment-setting" "Have you been in a new environment?"
generate "chip-started-new-medication" "Have you started any new medication?"
generate "chip-ate-something-unusual" "Did you eat something unusual?"
generate "chip-strenuous-heavy-lifting" "Did you do any heavy lifting?"
generate "chip-prolonged-sitting-position" "Were you sitting for a long time?"
generate "chip-fight-assault-involvement" "Were you in a fight or assault?"
generate "chip-witnessed-traumatic-event" "Did you witness anything traumatic?"
generate "chip-severe-pain-at-injury-site" "Do you have severe pain at the injury site?"
generate "chip-visible-bleeding" "Where are you bleeding from?"
generate "chip-active-arterial-bleeding" "Is the bleeding spurting or pulsating?"
generate "chip-numbness-tingling-distal" "Do you feel numbness or tingling in the area beyond the injury?"
generate "chip-loss-of-limb-function" "Can you move the injured limb?"
generate "chip-pulseless-cold-extremity" "Does the limb feel cold or have no pulse?"
generate "chip-pale-cyanotic-skin" "Does the skin look pale or bluish?"
generate "chip-cold-clammy-shock-signs" "Do you feel cold and clammy?"
generate "chip-coughing-blood-hemoptysis" "Are you coughing up blood?"
generate "chip-loss-of-consciousness-any" "Did you lose consciousness at any point?"
generate "chip-confused-disoriented" "Do you feel confused or disoriented?"
generate "chip-vomiting-after-injury" "Have you vomited since the injury?"
generate "chip-visual-disturbance" "Has your vision changed?"
generate "chip-tinnitus-hearing-loss" "Do you have ringing in your ears or hearing loss?"
generate "chip-severe-headache-after-impact" "Did you get a severe headache after the impact?"
generate "chip-inability-to-bear-weight" "Can you put weight on it?"
generate "chip-deformity-visible" "Is the area visibly deformed?"
generate "chip-combative-agitated" "Are you feeling agitated?"
generate "chip-adhesive-tape-bandage" "Are you allergic to adhesive tape or bandages?"
generate "chip-iodine-antiseptic" "Are you allergic to iodine or antiseptic solution?"
generate "chip-aspirin-nsaids-analgesic" "Are you allergic to aspirin or pain relievers?"
generate "chip-opioids-morphine" "Are you allergic to opioids or morphine?"
generate "chip-tetanus-toxoid" "Are you allergic to the tetanus vaccine?"
generate "chip-contrast-media-iodine-iv" "Are you allergic to IV contrast or iodine?"
generate "chip-bee-wasp-stings" "Have you ever had a severe reaction to bee or wasp stings?"
generate "chip-blood-thinners-warfarin" "Are you taking blood thinners or warfarin?"
generate "chip-antiplatelets-aspirin-plavix" "Are you taking aspirin or other antiplatelet medication?"
generate "chip-insulin-diabetes-meds" "Are you taking insulin or diabetes medication?"
generate "chip-steroids-chronic" "Are you on chronic steroid therapy?"
generate "chip-opioid-pain-meds-chronic" "Are you on regular opioid pain medication?"
generate "chip-inhaler-copd-meds" "Do you use an inhaler for asthma or COPD?"
generate "chip-nitroglycerin-heart" "Do you take nitroglycerin for your heart?"
generate "chip-recent-alcohol-use" "How much alcohol have you had recently?"
generate "chip-recreational-drug-use" "Have you used any recreational drugs recently?"
generate "chip-tetanus-vaccine-status-unclear" "Do you know when your last tetanus shot was?"
generate "chip-bleeding-clotting-disorder" "Do you have a bleeding or clotting disorder?"
generate "chip-coronary-artery-disease" "Do you have coronary artery disease?"
generate "chip-hypertension" "Do you have high blood pressure?"
generate "chip-copd-asthma" "Do you have COPD or asthma?"
generate "chip-prior-stroke-tia" "Have you had a stroke or TIA before?"
generate "chip-seizure-disorder" "Do you have a seizure disorder?"
generate "chip-osteoporosis-fracture-risk" "Do you have osteoporosis or weak bones?"
generate "chip-prior-spinal-surgery" "Have you had spine surgery before?"
generate "chip-prior-joint-replacement" "Have you had a joint replacement?"
generate "chip-prior-similar-injury-same-area" "Have you injured this same area before?"
generate "chip-pacemaker-icd" "Do you have a pacemaker or implanted defibrillator?"
generate "chip-hemophilia-bleeding-disorder" "Do you have hemophilia or a bleeding disorder?"
generate "chip-mental-health-ptsd" "Do you have any mental health conditions or PTSD?"
generate "chip-alcohol-consumed-recent" "How recently did you drink alcohol?"
generate "chip-heavy-alcohol-intake" "Did you drink a lot of alcohol today?"
generate "chip-recreational-drugs" "Have you taken any recreational drugs?"
generate "chip-npo-already-pre-op" "Have you been told not to eat for a procedure?"
generate "chip-cannot-swallow-dysphagia" "Are you able to swallow?"
generate "chip-coffee-energy-drink" "Have you had coffee or an energy drink?"
generate "chip-sports-drink" "Have you had a sports drink?"
generate "chip-pain-medication-taken" "Did you take any pain medication?"
generate "chip-last-fluid-6-hours-ago" "When did you last have anything to drink?"
generate "chip-diabetic-last-meal-critical" "When did you last eat? It is critical because of your diabetes."
generate "chip-just-before-incident" "Did you eat or drink just before the injury?"
generate "chip-motor-vehicle-crash-mvc" "Were you in a vehicle crash?"
generate "chip-motorcycle-bicycle-crash" "Were you in a motorcycle or bicycle crash?"
generate "chip-fall-from-height" "Did you fall from a height?"
generate "chip-slip-on-wet-icy-surface" "Did you slip on a wet or icy surface?"
generate "chip-sports-recreational-injury" "Were you injured during sports?"
generate "chip-training-drill-incident" "Were you injured during training?"
generate "chip-industrial-workplace-accident" "Were you injured at work?"
generate "chip-machinery-crush" "Were you crushed or caught in machinery?"
generate "chip-assault-fight" "Were you in a fight or assaulted?"
generate "chip-domestic-violence" "Were you injured by someone you know?"
generate "chip-burn-thermal-chemical-electric" "Were you burned by heat, chemicals, or electricity?"
generate "chip-drowning-near-drowning" "Were you in a water accident?"
generate "chip-animal-bite-attack" "Were you bitten or attacked by an animal?"
generate "chip-mechanism-unknown-unwitnessed" "Do you remember how this happened?"
generate "aed-if-you-need-help-call-for-emergency-medical-servic" "If you need help, call for emergency medical services now."
generate "aed-pull-the-green-handle-to-access-the-pads" "Pull the green handle to access the pads."
generate "aed-remove-all-clothing-from-the-patient-s-chest-cut-c" "Remove all clothing from the patient's chest. Cut clothing if needed."
generate "aed-wipe-sweat-or-moisture-from-the-chest" "Wipe sweat or moisture from the chest."
generate "aed-tear-open-the-white-pads-pouch" "Tear open the white pads pouch."
generate "aed-peel-one-pad-from-the-yellow-plastic-liner" "Peel one pad from the yellow plastic liner."
generate "aed-place-the-pad-on-bare-skin-exactly-as-shown-in-the" "Place the pad on bare skin exactly as shown in the picture on the pad."
generate "aed-peel-and-place-the-second-pad-as-shown" "Peel and place the second pad as shown."
generate "aed-press-the-pads-firmly-to-the-patient-s-bare-skin" "Press the pads firmly to the patient's bare skin."
generate "aed-plug-pads-connector-in-next-to-the-flashing-light" "Plug pads connector in next to the flashing light."
generate "aed-wait-while-heartstart-prepares-to-analyze-the-hear" "Wait while HeartStart prepares to analyze the heart rhythm."
generate "aed-analyzing-heart-rhythm-do-not-touch-the-patient" "Analyzing heart rhythm. Do not touch the patient."
generate "aed-analysis-interrupted-stop-all-motion" "Analysis interrupted. Stop all motion."
generate "aed-shock-advised" "Shock advised."
generate "aed-stay-clear-of-patient-deliver-shock-now-press-the-" "Stay clear of patient. Deliver shock now. Press the flashing orange button now."
generate "aed-shock-delivered" "Shock delivered."
generate "aed-it-is-now-safe-to-touch-the-patient" "It is now safe to touch the patient."
generate "aed-no-shock-advised-it-is-safe-to-touch-the-patient" "No shock advised. It is safe to touch the patient."
generate "aed-if-needed-begin-cpr-start-by-giving-thirty-chest-c" "If needed, begin CPR. Start by giving thirty chest compressions."
generate "aed-begin-cpr-place-the-heel-of-your-hand-on-the-breas" "Begin CPR. Place the heel of your hand on the breastbone in the center of the chest."
generate "aed-place-your-other-hand-on-top-interlocking-your-fin" "Place your other hand on top, interlocking your fingers."
generate "aed-push-down-firmly-two-inches-in-the-center-of-the-c" "Push down firmly two inches in the center of the chest."
generate "aed-push-and-let-go-push-and-let-go" "Push and let go, push and let go."
generate "aed-give-two-breaths" "Give two breaths."
generate "aed-continue-with-thirty-compressions" "Continue with thirty compressions."
generate "aed-stop-cpr-pause-briefly-while-heartstart-analyzes-t" "Stop CPR. Pause briefly while HeartStart analyzes the heart rhythm. Do not touch the patient."
generate "aed-infant-child-key-inserted-use-on-patient-less-than" "Infant child key inserted. Use on patient less than fifty five pounds or eight years old."
generate "aed-apply-pad-to-the-center-of-the-patient-s-chest-dir" "Apply pad to the center of the patient's chest, directly between the nipples."
generate "aed-apply-the-other-pad-to-the-center-of-the-patient-s" "Apply the other pad to the center of the patient's back."
generate "aed-battery-low-replace-battery" "Battery low. Replace battery."
generate "aed-insert-battery-into-heartstart" "Insert battery into HeartStart."
generate "aed-pads-non-functional-replace-pads" "Pads non-functional. Replace pads."
generate "aed-service-required" "Service required."

echo
echo "✅  Done. Generated $(ls -1 $OUT_DIR/*.${EXT} 2>/dev/null | wc -l | tr -d ' ') files in $OUT_DIR/"
echo
echo "Next step:"
echo "  • Commit and push the audio/ folder to your GitHub repo alongside index.html."
echo "  • The PWA fetches each MP3 on demand — instant startup, no cutoffs."

# ── v2.9 audio fixes: Provocation (P) chips + newly-voiced questions ──
generate "chip-worse-with-exertion" "Does it get worse when you move or exert yourself?"
generate "chip-worse-with-deep-breath" "Does it get worse when you take a deep breath?"
generate "chip-worse-with-cough" "Does coughing make it worse?"
generate "chip-worse-after-eating" "Does it get worse after eating?"
generate "chip-worse-when-lying-flat" "Does lying flat make it worse?"
generate "chip-worse-when-standing" "Does standing make it worse?"
generate "chip-worse-with-stress" "Does stress make it worse?"
generate "chip-worse-in-heat-cold" "Does heat or cold make it worse?"
generate "chip-better-with-rest" "Does resting make it better?"
generate "chip-better-sitting-forward" "Does sitting forward make it better?"
generate "chip-better-lying-still" "Does lying still make it better?"
generate "chip-better-after-medication" "Does medication make it better?"
generate "chip-better-after-inhaler" "Does your inhaler make it better?"
generate "chip-better-after-vomiting" "Did it get better after vomiting?"
generate "chip-better-after-bowel-movement" "Did it get better after a bowel movement?"
generate "chip-no-position-helps" "Is there no position that helps?"
generate "chip-comes-with-activity" "Does it come on with activity?"
generate "chip-comes-at-rest" "Does it happen even at rest?"
generate "chip-touch-does-not-change-it" "Does touching it make no difference?"
generate "chip-other-pattern" "Is there another pattern that changes it?"
generate "chip-after-alcohol-consumption" "Did this start after drinking alcohol?"
generate "chip-after-eating-a-meal" "Did this start after you ate a meal?"
generate "chip-antidepressants-ssris" "Do you take antidepressants or SSRIs?"
generate "chip-anxiolytics-benzodiazepines" "Do you take anti-anxiety medicine or benzodiazepines?"
generate "chip-bowel-bladder-change-recently" "Have you had any recent change in your bowel or bladder habits?"
generate "chip-cancer-history" "Do you have a history of cancer?"
generate "chip-chemotherapy" "Are you receiving chemotherapy?"
generate "chip-eggs-dairy" "Are you allergic to eggs or dairy?"
generate "chip-epipen" "Do you carry an EpiPen?"
generate "chip-latex-rubber-gloves" "Are you allergic to latex?"
generate "chip-no-remarkable-history" "Do you have any significant medical history?"
generate "chip-numbness-with-tingling" "Do you feel numbness or tingling?"
generate "chip-penicillin-antibiotics" "Are you allergic to penicillin or antibiotics?"
generate "chip-pollen-environmental" "Do you have pollen or environmental allergies?"
generate "chip-pregnancy-related-symptoms" "Could your symptoms be related to pregnancy?"
generate "chip-recent-infection-cold" "Have you had a recent cold or infection?"
generate "chip-shellfish" "Are you allergic to shellfish?"
generate "ask-relationship" "What is your relationship to the patient?"
# v2.9.16 audio fixes: personal-info prompts (MP3) + P-cause question + new O chips
generate "ask-name" "What is your name?"
generate "ask-dob" "What is your date of birth? Month, day, and year please."
generate "ask-ssn" "What is your Social Security Number?"
generate "ask-phone" "What is your phone number?"
generate "ask-unit" "What is your unit or command?"
generate "opqrst-p-cause" "Can you think of anything that may have caused this? Is there anything that comes to mind?"
generate "chip-working-outdoors" "Were you working outdoors when it started?"
generate "chip-on-regular-duty-working" "Were you on your regular duties when it started?"
# v2.9.18 E (events) chip audio
generate "chip-sudden-unusual-exertion" "Did you do any sudden or unusual physical exertion?"
generate "chip-trouble-concentrating" "Have you been unable to concentrate or feeling foggy?"
generate "chip-skipped-meals-poor-appetite" "Have you skipped meals or had a poor appetite?"
generate "chip-poor-fluid-intake" "Have you been drinking less fluid than usual?"
generate "chip-worked-in-extreme-heat" "Have you been working in extreme heat?"
generate "chip-cold-exposure" "Have you been exposed to cold?"
generate "chip-unusual-diet" "Did you eat anything different from usual?"
generate "chip-felt-off-all-day" "Have you been feeling off all day?"
# v3.5 trauma injury-cause chip audio
generate "chip-machine-equipment-malfunction" "Did a machine or equipment malfunction cause this?"
generate "chip-slipped-on-road-surface" "Did you slip on the road surface?"
generate "chip-tripped-lost-footing" "Did you trip or lose your footing?"
generate "chip-poor-visibility" "Was visibility poor at the time?"
generate "chip-excessive-speed" "Was excessive speed involved?"
generate "chip-inattention-distraction" "Were you distracted or not paying attention?"
generate "chip-fatigue-drowsy" "Were you tired or drowsy?"
generate "chip-alcohol-drugs" "Had you taken any alcohol or drugs?"
generate "chip-sudden-movement-overexertion" "Did a sudden movement or overexertion cause this?"
generate "chip-falling-dropped-object" "Were you hit by a falling or dropped object?"
generate "chip-unstable-footing-high-place" "Were you on unstable footing or in a high place?"
generate "chip-wet-slippery-floor" "Was the floor wet or slippery?"
generate "chip-another-person-vehicle-involved" "Was another person or vehicle involved?"
generate "chip-weather-road-conditions" "Did the weather or road conditions contribute?"
generate "chip-improper-ppe-safety-gear" "Were you missing proper safety gear?"
generate "chip-unknown-cannot-identify" "Can you think of any possible cause?"
generate "dots-intro" "I am now going to examine your body from head to toe to check for injuries. I will touch you gently. Please tell me right away if any area hurts. Try to stay still and do not move."
